name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:

  release:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5

      - name: Download References
        uses: Axwabo/scpsl-references-downloader@v1
        with: 
          branch: ${{ vars.BRANCH }}

      - name: Download SCPSL-Helpers
        uses: robinraju/release-downloader@v1.12
        with:
          repository: "Axwabo/SCPSL-Helpers"
          latest: true
          fileName: '*'
          out-file-path: ${{ env.ReferencePath }}

      - name: Build
        run: dotnet build Axwabo.CommandSystem -c Release -o Output

      - name: Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: "Output/Axwabo.CommandSystem.dll,Output/Axwabo.CommandSystem.xml"
